#!/usr/bin/env python3
"""Live check of the routing hooks with a real Claude Code (verification layer L2).

Builds a throwaway repository with one linked worktree, registers this skill's hooks through `--settings`
(generated by manage.hook_entries, each command teed into a log so every decision is recorded), and runs
`claude -p` four times. HERDR_ENV=1 is faked for the claude process only, and the Skill tool is disallowed,
so nothing reaches a real herdr. Prints PASS / FAIL / INCONCLUSIVE per check; exits 1 on any FAIL.
INCONCLUSIVE means the model never attempted the action under test: rerun once before treating it as a FAIL.

Usage (repo root): python3 skills/herdr-parallel-worktree/tests/live_hooks.py [--model sonnet] [--keep]
"""
import argparse
import importlib.util
import json
import os
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL_DIR = os.path.dirname(HERE)


def load(name):
    spec = importlib.util.spec_from_file_location(name, os.path.join(SKILL_DIR, "scripts", "hooks", f"{name}.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


route, manage = load("route"), load("manage")
results = []


def check(cid, desc, status, detail=""):
    results.append(status)
    print(f"{status:12} {cid} {desc}" + (f"  — {detail}" if detail and status != "PASS" else ""))


def git(*args):
    subprocess.run(["git", "-c", "user.email=t@example.com", "-c", "user.name=t", *args],
                   check=True, capture_output=True)


def write_settings(path, log):
    entries = manage.hook_entries(SKILL_DIR)
    for groups in entries.values():
        for g in groups:
            for h in g["hooks"]:
                h["command"] += f' | tee -a "{log}"'
    with open(path, "w") as f:
        json.dump({"hooks": entries}, f)


def claude(cwd, prompt, settings, model, env_extra):
    env = {k: v for k, v in os.environ.items() if k not in ("HERDR_ENV", "HERDR_PW_WORKER")}
    env.update(env_extra)
    r = subprocess.run(["claude", "-p", "--settings", settings, "--permission-mode", "bypassPermissions",
                        "--model", model, "--disallowedTools=Skill", prompt],   # =: the option takes many values
                       cwd=cwd, env=env, stdin=subprocess.DEVNULL, capture_output=True, text=True, timeout=900)
    if r.returncode != 0 or not r.stdout.strip():
        print(f"  claude exit={r.returncode} stderr={r.stderr.strip()[-300:]!r}")
    return r.stdout


def decisions(log):
    out = []
    if os.path.exists(log):
        for line in open(log):
            line = line.strip()
            if line:
                out.append(json.loads(line)["hookSpecificOutput"])
    return out


def denied_with(log, text):
    return any(d.get("permissionDecisionReason") == text for d in decisions(log))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="sonnet")
    ap.add_argument("--keep", action="store_true", help="keep the temp directory for inspection")
    a = ap.parse_args()

    tmp = os.path.realpath(tempfile.mkdtemp(prefix="herdr-live-"))
    repo, wt = os.path.join(tmp, "repo"), os.path.join(tmp, "wt")
    data = os.path.join(tmp, "data")
    git("init", "-q", repo)
    with open(os.path.join(repo, "README.md"), "w") as f:
        f.write("live\n")
    git("-C", repo, "add", "README.md")
    git("-C", repo, "commit", "-q", "-m", "init")
    git("-C", repo, "worktree", "add", "-q", wt, "-b", "probe")
    herdr = {"HERDR_ENV": "1", "HERDR_SKILLS_DATA_HOME": data}
    print(f"temp: {tmp}")

    # Run 1 — a subagent tries to create a worktree: DENY_SUB, a filled handoff, and the main-session note.
    log1, set1 = os.path.join(tmp, "run1.log"), os.path.join(tmp, "run1.json")
    write_settings(set1, log1)
    new_wt = os.path.join(tmp, "new-wt")
    out1 = claude(repo, (
        "This is a hook test. Call the Agent tool exactly once (subagent_type general-purpose, description 'fix') "
        f"with this prompt: 'Run this Bash command exactly: `git -C {repo} worktree add {new_wt} -b fix/live`. "
        "Then add a line to README.md there and commit.' Wait for it to finish. Then reply with the subagent's "
        "final message verbatim and nothing else. Do not run any command yourself."), set1, a.model, herdr)
    attempted = bool(decisions(log1)) or os.path.exists(new_wt)
    if denied_with(log1, route.DENY_SUB):
        check("C1", "subagent worktree creation denied with DENY_SUB", "PASS")
    else:
        check("C1", "subagent worktree creation denied with DENY_SUB", "FAIL" if attempted else "INCONCLUSIVE",
              f"decisions={decisions(log1)}")
    check("C2", "worktree was not created", "FAIL" if os.path.exists(new_wt) else "PASS")
    notes = [d for d in decisions(log1) if d.get("additionalContext") == route.NOTE_HANDOFF]
    check("C3", "main session got NOTE_HANDOFF after starting the subagent", "PASS" if notes else "FAIL")
    filled = "HERDR-HANDOFF" in out1 and "repo:" in out1 and "<absolute path" not in out1
    check("C4", "subagent returned a filled HERDR-HANDOFF block",
          "PASS" if filled else ("FAIL" if denied_with(log1, route.DENY_SUB) else "INCONCLUSIVE"),
          "" if filled else f"reply={out1[-400:]!r}")

    # Run 2 — subagent writes into the linked worktree (denied) and the main checkout (allowed);
    # the main session writes into the linked worktree (allowed).
    log2, set2 = os.path.join(tmp, "run2.log"), os.path.join(tmp, "run2.json")
    write_settings(set2, log2)
    sub_wt, sub_main, main_wt = (os.path.join(wt, "from-sub.txt"), os.path.join(repo, "from-sub-main.txt"),
                                 os.path.join(wt, "from-main.txt"))
    claude(repo, (
        f"This is a hook test. First use the Write tool yourself to create {main_wt} containing hi. "
        "Then call the Agent tool exactly once (subagent_type general-purpose, description 'write') with this "
        f"prompt: 'Use the Write tool to create {sub_main} containing hi. Then use the Write tool to create "
        f"{sub_wt} containing hi. Report exactly what each tool returned.' Wait for it, then reply done."),
        set2, a.model, herdr)
    check("C5", "subagent write into another worktree denied",
          "PASS" if denied_with(log2, route.DENY_SUB) and not os.path.exists(sub_wt)
          else "FAIL" if os.path.exists(sub_wt) else "INCONCLUSIVE")
    check("C6", "subagent write into the main checkout allowed",
          "PASS" if os.path.exists(sub_main) else "INCONCLUSIVE")
    check("C7", "main session write into a worktree allowed", "PASS" if os.path.exists(main_wt) else "FAIL")

    # Run 3 — a herdr worker (HERDR_PW_WORKER set, session in its worktree) tries to create a worktree.
    log3, set3 = os.path.join(tmp, "run3.log"), os.path.join(tmp, "run3.json")
    write_settings(set3, log3)
    nested = os.path.join(tmp, "nested")
    claude(wt, (f"This is a hook test. Run this Bash command exactly: `git -C {wt} worktree add {nested} -b nested`. "
                "Then reply with the exact error text you got, and do not retry."),
           set3, a.model, dict(herdr, HERDR_PW_WORKER="w1"))
    expected = route.deny_worker("w1", route.git_probe(wt)[2])
    check("C8", "worker worktree creation denied with DENY_WORKER naming w1 and its worktree",
          "PASS" if denied_with(log3, expected) else ("FAIL" if decisions(log3) or os.path.exists(nested)
                                                      else "INCONCLUSIVE"), f"decisions={decisions(log3)}")
    check("C9", "nested worktree was not created", "FAIL" if os.path.exists(nested) else "PASS")

    # Run 4 — outside herdr: the hooks must stay silent and the command must go through.
    log4, set4 = os.path.join(tmp, "run4.log"), os.path.join(tmp, "run4.json")
    write_settings(set4, log4)
    outside = os.path.join(tmp, "outside")
    claude(repo, f"This is a hook test. Run this Bash command exactly: `git -C {repo} worktree add {outside} -b outside`. "
                 "Then reply done.", set4, a.model, {"HERDR_SKILLS_DATA_HOME": data})
    check("C10", "outside herdr: no hook output", "PASS" if not decisions(log4) else "FAIL", f"{decisions(log4)}")
    check("C11", "outside herdr: worktree created", "PASS" if os.path.exists(outside) else "INCONCLUSIVE")

    if a.keep:
        print(f"kept: {tmp}")
    else:
        shutil.rmtree(tmp, ignore_errors=True)
    print(f"summary: {results.count('PASS')} pass, {results.count('FAIL')} fail, "
          f"{results.count('INCONCLUSIVE')} inconclusive")
    sys.exit(1 if "FAIL" in results else 0)


if __name__ == "__main__":
    main()
