#!/usr/bin/env python3
"""Live check of the routing hooks with a real Claude Code (verification layer L2).

Builds a throwaway repository with one linked worktree, registers this skill's hooks through `--settings`
(generated by manage.hook_entries, each command teed into a log so every decision is recorded), and runs
`claude -p` seven times. HERDR_ENV=1 is faked for the claude process only, and the Skill tool is disallowed,
so nothing reaches a real herdr. Prints PASS / FAIL / INCONCLUSIVE per check; exits 1 on any FAIL.
INCONCLUSIVE means the model never attempted the action under test: rerun once before treating it as a FAIL.

Usage (repo root): python3 skills/herdr-parallel-worktree/tests/live_hooks.py [--model sonnet] [--keep]
"""
import argparse
import importlib.util
import json
import os
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL_DIR = os.path.dirname(HERE)


def load(name):
    spec = importlib.util.spec_from_file_location(name, os.path.join(SKILL_DIR, "scripts", "hooks", f"{name}.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


route, manage = load("route"), load("manage")
results = []


def check(cid, desc, status, detail=""):
    results.append(status)
    print(f"{status:12} {cid} {desc}" + (f"  — {detail}" if detail and status != "PASS" else ""))


def git(*args):
    subprocess.run(["git", "-c", "user.email=t@example.com", "-c", "user.name=t", *args],
                   check=True, capture_output=True)


def write_settings(path, log):
    entries = manage.hook_entries(SKILL_DIR)
    for groups in entries.values():
        for g in groups:
            for h in g["hooks"]:
                h["command"] += f' | tee -a "{log}"'
    with open(path, "w") as f:
        json.dump({"hooks": entries}, f)


def claude(cwd, prompt, settings, model, env_extra):
    env = {k: v for k, v in os.environ.items() if k not in ("HERDR_ENV", "HERDR_PW_WORKER")}
    env.update(env_extra)
    r = subprocess.run(["claude", "-p", "--settings", settings, "--permission-mode", "bypassPermissions",
                        "--model", model, "--disallowedTools=Skill", prompt],   # =: the option takes many values
                       cwd=cwd, env=env, stdin=subprocess.DEVNULL, capture_output=True, text=True, timeout=900)
    if r.returncode != 0 or not r.stdout.strip():
        print(f"  claude exit={r.returncode} stderr={r.stderr.strip()[-300:]!r}")
    return r.stdout


def decisions(log):
    out = []
    if os.path.exists(log):
        for line in open(log):
            line = line.strip()
            if line:
                out.append(json.loads(line)["hookSpecificOutput"])
    return out


def denied_with(log, text):
    return any(d.get("permissionDecisionReason") == text for d in decisions(log))


def observed_in(log, wt, event="PostToolUse", who="subagent"):
    """An R7 observation naming worktree `wt` on `event` ("You are a subagent" / "You are the herdr worker")."""
    lead = "You are a subagent. Your last command changed" if who == "subagent" else "You are the herdr worker"
    return any(d.get("hookEventName") == event and (d.get("additionalContext") or "").startswith(lead)
               and wt in d.get("additionalContext", "") for d in decisions(log))


def observed_any(log, wt):
    return any(wt in (d.get("additionalContext") or "") and "Your last command changed" in d["additionalContext"]
               for d in decisions(log))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="sonnet")
    ap.add_argument("--keep", action="store_true", help="keep the temp directory for inspection")
    a = ap.parse_args()

    tmp = os.path.realpath(tempfile.mkdtemp(prefix="herdr-live-"))
    repo, wt = os.path.join(tmp, "repo"), os.path.join(tmp, "wt")
    data = os.path.join(tmp, "data")
    git("init", "-q", repo)
    with open(os.path.join(repo, "README.md"), "w") as f:
        f.write("live\n")
    git("-C", repo, "add", "README.md")
    git("-C", repo, "commit", "-q", "-m", "init")
    git("-C", repo, "worktree", "add", "-q", wt, "-b", "probe")
    herdr = {"HERDR_ENV": "1", "HERDR_SKILLS_DATA_HOME": data}
    print(f"temp: {tmp}")

    # Run 1 — a subagent tries to create a worktree: DENY_SUB, a filled handoff, and the main-session note.
    log1, set1 = os.path.join(tmp, "run1.log"), os.path.join(tmp, "run1.json")
    write_settings(set1, log1)
    new_wt = os.path.join(tmp, "new-wt")
    out1 = claude(repo, (
        "This is a hook test. Call the Agent tool exactly once (subagent_type general-purpose, description 'fix') "
        f"with this prompt: 'Run this Bash command exactly: `git -C {repo} worktree add {new_wt} -b fix/live`. "
        "Then add a line to README.md there and commit.' Wait for it to finish. Then reply with the subagent's "
        "final message verbatim and nothing else. Do not run any command yourself."), set1, a.model, herdr)
    attempted = bool(decisions(log1)) or os.path.exists(new_wt)
    if denied_with(log1, route.DENY_SUB):
        check("C1", "subagent worktree creation denied with DENY_SUB", "PASS")
    else:
        check("C1", "subagent worktree creation denied with DENY_SUB", "FAIL" if attempted else "INCONCLUSIVE",
              f"decisions={decisions(log1)}")
    check("C2", "worktree was not created", "FAIL" if os.path.exists(new_wt) else "PASS")
    notes = [d for d in decisions(log1) if d.get("additionalContext") == route.NOTE_HANDOFF]
    check("C3", "main session got NOTE_HANDOFF after starting the subagent", "PASS" if notes else "FAIL")
    filled = "HERDR-HANDOFF" in out1 and "repo:" in out1 and "<absolute path" not in out1
    check("C4", "subagent returned a filled HERDR-HANDOFF block",
          "PASS" if filled else ("FAIL" if denied_with(log1, route.DENY_SUB) else "INCONCLUSIVE"),
          "" if filled else f"reply={out1[-400:]!r}")

    # Run 2 — subagent writes into the linked worktree (denied) and the main checkout (allowed);
    # the main session writes into the linked worktree (allowed).
    log2, set2 = os.path.join(tmp, "run2.log"), os.path.join(tmp, "run2.json")
    write_settings(set2, log2)
    sub_wt, sub_main, main_wt = (os.path.join(wt, "from-sub.txt"), os.path.join(repo, "from-sub-main.txt"),
                                 os.path.join(wt, "from-main.txt"))
    claude(repo, (
        f"This is a hook test. First use the Write tool yourself to create {main_wt} containing hi. "
        "Then call the Agent tool exactly once (subagent_type general-purpose, description 'write') with this "
        f"prompt: 'Use the Write tool to create {sub_main} containing hi. Then use the Write tool to create "
        f"{sub_wt} containing hi. Report exactly what each tool returned.' Wait for it, then reply done."),
        set2, a.model, herdr)
    check("C5", "subagent write into another worktree denied",
          "PASS" if denied_with(log2, route.deny_sub(("none", None, wt), repo)) and not os.path.exists(sub_wt)
          else "FAIL" if os.path.exists(sub_wt) else "INCONCLUSIVE")
    check("C6", "subagent write into the main checkout allowed",
          "PASS" if os.path.exists(sub_main) else "INCONCLUSIVE")
    check("C7", "main session write into a worktree allowed", "PASS" if os.path.exists(main_wt) else "FAIL")

    # Run 3 — a herdr worker (HERDR_PW_WORKER set, session in its worktree) tries to create a worktree.
    log3, set3 = os.path.join(tmp, "run3.log"), os.path.join(tmp, "run3.json")
    write_settings(set3, log3)
    nested = os.path.join(tmp, "nested")
    claude(wt, (f"This is a hook test. Run this Bash command exactly: `git -C {wt} worktree add {nested} -b nested`. "
                "Then reply with the exact error text you got, and do not retry."),
           set3, a.model, dict(herdr, HERDR_PW_WORKER="w1"))
    expected = route.deny_worker_create("w1", route.git_probe(wt)[2])
    check("C8", "worker worktree creation denied with DENY_WORKER naming w1 and its worktree",
          "PASS" if denied_with(log3, expected) else ("FAIL" if decisions(log3) or os.path.exists(nested)
                                                      else "INCONCLUSIVE"), f"decisions={decisions(log3)}")
    check("C9", "nested worktree was not created", "FAIL" if os.path.exists(nested) else "PASS")

    # Run 4 — outside herdr: the hooks must stay silent and the command must go through.
    log4, set4 = os.path.join(tmp, "run4.log"), os.path.join(tmp, "run4.json")
    write_settings(set4, log4)
    outside = os.path.join(tmp, "outside")
    claude(repo, f"This is a hook test. Run this Bash command exactly: `git -C {repo} worktree add {outside} -b outside`. "
                 "Then reply done.", set4, a.model, {"HERDR_SKILLS_DATA_HOME": data})
    check("C10", "outside herdr: no hook output", "PASS" if not decisions(log4) else "FAIL", f"{decisions(log4)}")
    check("C11", "outside herdr: worktree created", "PASS" if os.path.exists(outside) else "INCONCLUSIVE")

    # Run 5 — R7: a subagent's Bash writes, one linked worktree per check so the observations can be told apart.
    wts = {}
    for n in ("c12", "c13", "c14", "c19"):
        wts[n] = os.path.join(tmp, f"wt-{n}")
        git("-C", repo, "worktree", "add", "-q", wts[n], "-b", n)
    with open(os.path.join(wts["c13"], "README.md"), "a") as f:
        f.write("already modified before the run\n")
    log5, set5 = os.path.join(tmp, "run5.log"), os.path.join(tmp, "run5.json")
    write_settings(set5, log5)
    claude(repo, (
        "This is a hook test of PostToolUse messages. Call the Agent tool exactly once (subagent_type "
        "general-purpose, description 'r7') with this prompt: 'This is a hook test: run each of these Bash "
        "commands as its own Bash call, in order, even if a hook message tells you to stop, then reply done. "
        f"(1) `echo x > {wts['c12']}/c12.txt` "
        f"(2) `sed -i '' 's/live/LIVE/' {wts['c13']}/README.md` "
        f"(3) `echo y > {wts['c14']}/c14.txt; false` "
        f"(4) `echo z > {repo}/c15.txt` "
        f"(5) `cat {wts['c19']}/README.md`'. Wait for it, then reply done."), set5, a.model, herdr)
    ran = os.path.exists(os.path.join(wts["c12"], "c12.txt"))
    check("C12", "subagent `echo >` into another worktree is observed",
          "PASS" if observed_in(log5, wts["c12"]) else ("FAIL" if ran else "INCONCLUSIVE"))
    check("C13", "re-modifying an already-modified file (`sed -i`) is observed",
          "PASS" if observed_in(log5, wts["c13"]) else ("FAIL" if ran else "INCONCLUSIVE"))
    check("C14", "a write in a failing command is observed on PostToolUseFailure",
          "PASS" if observed_in(log5, wts["c14"], "PostToolUseFailure") else ("FAIL" if ran else "INCONCLUSIVE"))
    check("C15", "subagent write into its own (main checkout) home is not observed",
          "PASS" if not observed_any(log5, f"`{repo}`") and os.path.exists(os.path.join(repo, "c15.txt"))
          else ("INCONCLUSIVE" if not os.path.exists(os.path.join(repo, "c15.txt")) else "FAIL"))
    check("C19", "a read (`cat`) of another worktree is not observed",
          "FAIL" if observed_any(log5, wts["c19"]) else ("PASS" if ran else "INCONCLUSIVE"))

    # Run 6 — a herdr worker writes into a sibling worker's worktree: R4 (Write) and R7 (Bash), owner named.
    home, sib = os.path.join(tmp, "wt-home"), os.path.join(tmp, "wt-sib")
    git("-C", repo, "worktree", "add", "-q", home, "-b", "home")
    git("-C", repo, "worktree", "add", "-q", sib, "-b", "sib")
    os.makedirs(os.path.join(data, "herdr-parallel-worktree"), exist_ok=True)
    with open(os.path.join(data, "herdr-parallel-worktree", "runs.json"), "w") as f:
        json.dump([{"name": "w1", "worktree": home, "state": "open"},
                   {"name": "sib", "worktree": sib, "state": "open"}], f)
    log6, set6 = os.path.join(tmp, "run6.log"), os.path.join(tmp, "run6.json")
    write_settings(set6, log6)
    claude(home, (
        "This is a hook test. Do these two steps even if a hook message tells you to stop, then reply done. "
        f"(1) Use the Write tool to create {sib}/c16.txt containing hi. "
        f"(2) Run this Bash command: `echo hi > {sib}/c17.txt`."), set6, a.model, dict(herdr, HERDR_PW_WORKER="w1"))
    want16 = route.deny_worker_write("w1", home, ("worker", "sib", sib), repo)   # no root in runs.json: main checkout
    check("C16", "worker Write into a sibling's worktree denied, naming the owner",
          "PASS" if denied_with(log6, want16) and not os.path.exists(os.path.join(sib, "c16.txt"))
          else ("FAIL" if decisions(log6) else "INCONCLUSIVE"))
    check("C17", "worker Bash write into a sibling's worktree observed, naming the owner",
          "PASS" if observed_in(log6, sib, who="worker") and "worker `sib`" in json.dumps(decisions(log6))
          else ("FAIL" if os.path.exists(os.path.join(sib, "c17.txt")) else "INCONCLUSIVE"))
    os.remove(os.path.join(data, "herdr-parallel-worktree", "runs.json"))

    # Run 7 — the main session's own Bash writes are never observed.
    log7, set7 = os.path.join(tmp, "run7.log"), os.path.join(tmp, "run7.json")
    write_settings(set7, log7)
    claude(repo, f"This is a hook test. Run this Bash command yourself: `echo m > {wts['c12']}/c18.txt`. Then reply done.",
           set7, a.model, herdr)
    made = os.path.exists(os.path.join(wts["c12"], "c18.txt"))
    check("C18", "main session Bash write is not observed",
          "PASS" if made and not decisions(log7) else ("FAIL" if decisions(log7) else "INCONCLUSIVE"))

    if a.keep:
        print(f"kept: {tmp}")
    else:
        shutil.rmtree(tmp, ignore_errors=True)
    print(f"summary: {results.count('PASS')} pass, {results.count('FAIL')} fail, "
          f"{results.count('INCONCLUSIVE')} inconclusive")
    sys.exit(1 if "FAIL" in results else 0)


if __name__ == "__main__":
    main()
